version: "3.9"
services:
  fsrs-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/fsrs-debug:${TAG}
    ports:
      - 2230:2230
      - 2222:22
    privileged: true
    network_mode: "host"     
    #volumes:
      #- type: bind
      #  source: /home/torizon/76er
      #  target: /home/torizon/76er
      #  - type: bind
    #    source: /home/torizon/budizledozer
    #    target: /home/torizon/budizledozer
      #- logini:/home/torizon

  fsrs:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/fsrs:${TAG}
    privileged: true
    network_mode: "host"